AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

  DisplayCopNames: true
  StyleGuideCopsOnly: false

Rails:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 22

Style/BarePercentLiterals:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false
